---
- hosts: webservers
  become: yes

  tasks:

  - name: Update apt
    apt:
      update_cache: yes

  - name: Install NodeJS
    apt:
      name:
        - nodejs
        - npm
      state: present

  - name: Create app directory
    file:
      path: /home/ubuntu/app
      state: directory

  - name: Copy app files
    copy:
      src: app/
      dest: /home/ubuntu/app/

  - name: Install dependencies
    npm:- hosts: loadbalancer
  become: yes

  tasks:

  - name: Install nginx
    apt:
      name: nginx
      state: present
      update_cache: yes

  - name: Configure nginx load balancer
    copy:
      dest: /etc/nginx/sites-available/default
      content: |
        upstream backend {
            server APP_SERVER_IP1:5000;
            server APP_SERVER_IP2:5000;
        }

        server {
            listen 80;

            location / {
                proxy_pass http://backend;
            }
        }

  - name: Restart nginx
    service:
      name: nginx
      state: restarted

      path: /home/ubuntu/app

  - name: Start application
    shell: |
      nohup node /home/ubuntu/app/index.js &

