[webservers]

server1 ansible_host=3.80.98.23 ansible_user=ubuntu
server2 ansible_host=18.209.162.229 ansible_user=ubuntu

[all:vars]
ansible_python_interpreter=/usr/bin/python3


[loadbalancer]

lb ansible_host=100.31.213.90  ansible_user=ubuntu
